trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: test
    displayName: "Run tests"
    services:
      docker: 
        image: docker:20.10.7-dind
        options: --privileged

    steps:
      - checkout: self

      - script: |
          set -x
          curl -L https://github.com/docker/compose/releases/download/v2.32.4/docker-compose-`uname -s`-`uname -m` > docker-compose
          chmod +x docker-compose
          sudo mv docker-compose /usr/local/bin/docker-compose
        displayName: "Install Docker Compose"

      - script: |
          set -x
          docker-compose build --build-arg BRANCH=$(Build.SourceBranchName) update
          docker-compose up -d

          TOMCAT_CONTAINER=$(docker ps --filter "name=-tomcat-1" --format "{{.Names}}" | head -n 1)
          
          if [ -z "$TOMCAT_CONTAINER" ]; then
            echo "❌ No running tomcat container found!"
            docker ps
            exit 1
          fi

          docker run --network container:$TOMCAT_CONTAINER \
            appropriate/curl -4 --retry 10 --retry-delay 60 --retry-connrefused http://tomcat:8080/api/authInfo
        displayName: "Start Aquality Tracking and Run Health Check"
