version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-node-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: Update Google chrome
          command: | 
              sudo apt-get update
              sudo apt-get install google-chrome-stable
              google-chrome --version

      - run: 
          name: Install docker-compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Start docker-compose
          command:  |
            cd api
            set -x
            docker-compose build --build-arg BRANCH=${CIRCLE_BRANCH} update
            docker-compose up -d
            docker run --network container:api_tomcat_1 \
              appropriate/curl --retry 20 --retry-delay 60 --retry-connrefused http://localhost:8080/api/authInfo

      - run: 
          name: Install dependencies
          command: npm i
            
      - run:
          name: Run tests
          command: npm run e2e:headless
            
      - run:
          when: always
          name: Generate allure
          command: npm run allure

      - store_artifacts:
          path: allure-report/
          
      - store_artifacts:
          path: allure-results/

