version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.15.3

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: Install docker-compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run: 
          name: Install java
          command: | 
            sudo apt-get -y -q update && \
            sudo apt-get -y -q upgrade && \
            sudo apt-get -y -q install software-properties-common htop && \
            sudo add-apt-repository ppa:webupd8team/java && \
            sudo apt-get -y -q update && \
            echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
            sudo apt-get -y -q install oracle-java8-installer && \
            sudo update-java-alternatives -s java-8-oracle

      - run:
          name: Start docker-compose
          command:  |
            cd api
            set -x
            docker-compose build --build-arg BRANCH=${CIRCLE_BRANCH} update
            docker-compose up -d
            docker run --network container:api_tomcat_1 \
              appropriate/curl --retry 20 --retry-delay 60 --retry-connrefused http://localhost:8080/api/authInfo

      - run:
          name: Run tests
          command: |
            docker build . -t tests
            docker run --network container:api_tomcat_1 \
              tests
      
      - run:
          when: always
          name: Generate allure
          command: npm run allure

      - store_test_results:
          path: allure-report/

